name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      - name: Download workflow artifact
  # You may pin to the exact commit or the version.
  # uses: dawidd6/action-download-artifact@86f3002f4e95a0ad10fa8514fe27e1dbfdcd190c
  uses: dawidd6/action-download-artifact@v2.9.0
  with:
    # GitHub token
    github_token: # optional, default is ${{github.token}}
    # Workflow name
    workflow: 
    # Repository name with owner (like actions/checkout)
    repo: # optional, default is ${{github.repository}}
    # Pull request number
    pr: # optional
    # Commit SHA1
    commit: # optional
    # Branch name
    branch: # optional
    # Workflow run id
    run_id: # optional
    # Artifact name (download all artifacts in not specified)
    name: # optional
    # Where to unpack the artifact
    path: # optional, default is ./
    - name: Upload a Build Artifact As-Is
  # You may pin to the exact commit or the version.
  # uses: kittaakos/upload-artifact-as-is@68d1b5ae1264196668586be0246d797bfc8980e5
  uses: kittaakos/upload-artifact-as-is@v0
  with:
    # A file, directory or wildcard pattern that describes what to upload
    path: 
